# Dependencies
markdown: redcarpet
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Silver Bullet
tagline: "Exploring desktop UI frameworks"
description: "Implementing a chat app in different GUI frameworks"
url: https://desktopui.github.io/silver-bullet
baseurl: /silver-bullet/

author:
  name: "Dmitry Loktev"
  url: https://twitter.com/potomushto

paginate: 5

# Custom vars
version: 2.1.0

github: [metadata]
